### PR TITLE
Use text for source & example links.

### PR DESCRIPTION
**Pull request by mbostock**
I feel this is both more self-evident and easier to maintain.

### CODE REVIEW

**Comment by Fil** [comment]
Yes!

I would just change to singular [Example], even when there are several:
- it's nicer to the eye, especially next to singular [Source]
- sometimes there is just one
- users will be looking for an example (ie _how do I use this function?_ rather than _what could I do with this?_, which is more the role of the gallery and the general collection)

**Comment by mbostock** [comment]
I’m okay capitalizing, but I think examples plural is appropriate because in the common case there will be more than one example.

**Comment by Fil** [comment]
Sorry I did not mean to capitalize, it was a slip of the keyboard.  But come to think of it it looks good :)
 
My only concern is that this [Source] [Examples] part is now more visible than the function's name. Maybe `<small>` like in the first line of the simulation below?

Capture d’écran 2019-05-10 à 21 55 43

Also, why the rel-nofollow?

**Comment by Fil** [comment]
(PS: don't bother applying whichever style to the whole file, at the end of this process I'll clean up and push a single commit.)

**Comment by mbostock** [comment]
GitHub sanitizes the styles, so `<small>` doesn’t work, sadly. ([See test.](https://github.com/d3/d3-geo-polygon/blob/cdec2d481a648d621e290767c1357dd64963e961/README.md))

**Comment by mbostock** [comment]
Made a few more typographic adjustments, but the design space is pretty limited by GitHub here.

**Comment by Fil** [comment]
Merged in https://github.com/d3/d3-geo-polygon/commit/2a18595b50d1ed28dfbedb76db687faae134f60a

**Pull request closed without merging**
