### PR TITLE
Imago projection

### PR DESCRIPTION
**Pull request by Fil**
Refs:
- https://observablehq.com/@fil/the-imago-projection
- https://github.com/d3/d3-geo-projection/issues/73
- https://observablehq.com/@fil/imago-projection-distorsion-analysis

imago

### CODE REVIEW

**Comment by waldyrious** [comment]
Are these artifacts expected?

screenshot 2019-02-28 at 10 53 35

**Comment by Fil** [comment]
I noticed that too. They are not here with k=0.68 but quite visible with
k=0.59.

**Comment by waldyrious** [comment]
Yeah, those seem to be the bisectors of the tetrahedron's sides:

Here's the initial image from @jkunimune15's [post](https://kunimune.home.blog/2017/11/23/the-secrets-of-the-authagraph-revealed/):

undistorted map

Here's an crudely annotated Imago projection, with k=0.4 to emphasize the artifacts:

annotated map

I suspect the original AuthaGraph projection was optimized so that the lines crossing those boundaries get curved to be perpendicular to them at the intersection points. Not sure if that can be directly translated to a specific (or even better, mathematically derived) _k_ value, or if they used another strategy (which might explain the small differences between the Imago and the original AuthaGraph).

**Comment by Fil** [comment]
Ha, very interesting observation! Then probably we should compute that
exact value, and mention it in the documentation.

**Comment by mciura** [comment]
FWIW, I had a similar problem in pseudo-Authagraph, but on the edges of the tetrahedron rather than on the bisectors of its faces. Without my (imperfect) smoothing, the projection was continuous but not differentiable at the joints between its parts. A possible solution is to replace the power function _f_(_r_) = _r_^_p_ by another function with the following properties:
* _f_(0) = 0,
* _f_(1) = 1,
* _f'_(1) chosen so that the projection is differentiable at joints (your experiments show that _f'_(1) should be approximately equal to 0.68; maybe the value can be derived),
* _f_(_r_) > _r_^0.68 for 0 < _r_ < 1 to reduce the distortion of lands,
* _f_(_r_) smooth for 0 < _r_ < 1, with large derivatives near 0.

**Comment by mciura** [comment]
Here is a sample function that satisfies the conditions:
* _f_(_r_) = 0.68 _r_ + 0.32 for _r_ > 0.1,
* _f_(_r_) = 0.470123339 _r_^0.0822622108 for 0 ≤ r ≤ 0.1.

**Comment by Fil** [comment]
@mciura if you want to add your function in src/imago.js : clone this repo, and checkout the imago branch. Then run:
- `yarn` to install the dependencies;
- `yarn test` to create dist/d3-geo-polygon.js
- `test/render-world imago > imago.png` or `test/render-world imago | imgcat` to create the test image

I have added an orientation map at https://observablehq.com/@fil/imago-projection-distorsion-analysis#ORIENTATION

**Comment by mciura** [comment]
@Fil Thank you for the instructions. I have tried a couple of functions different from the power function, with abysmal results. One conclusion is that keeping the lines of latitude above Antarctica nicely rounded depends on the values of the function in the entire [0, 1] interval.

**Comment by jkunimune15** [comment]
I've done some math, and assuming I've done this right, the value of k that prevents kinks seems to in fact be
equation)
or about 0.720.

**Comment by Fil** [comment]
The projection has been releaed with d3-geo-polygon 1.7.0.

The last mind-boggling question is to find the other rotations: one that allows to cut in the Bering Strait, and one that puts Antarctica on the left of the map.

**Comment by Fil** [comment]
And here is the first (I believe…) book to carry the Imago projection!

Photo le 13-05-2020 à 14 14

Photo le 13-05-2020 à 14 17

This projection was a perfect fit for the story arc: as you can read it from left to right to follow the action ("Peopling the planet"), main axis of movement, and direction of time.

**Pull request merged**
